apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-app1
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/yogesh-koli/test-argo.git 
    targetRevision: master 
    path: yogesh-koli/test-argo  # Path within the Git repository where manifests are located
  destination:
    server: test-1-dns-17jic8ac.hcp.centralus.azmk8s.io  # Kubernetes API server address
    namespace: argocd  
  syncPolicy:
    automated:
      prune: true  
      selfHeal: true  
